# Generated by Django 3.2.19 on 2023-10-11 06:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turist', '0001_initial'),
    ]

    operations = [

    ]
