# Generated by Django 3.2.19 on 2023-10-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0003_contenttourist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttourist',
            name='published_date',
        ),
    ]
