# Generated by Django 3.2.19 on 2023-10-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0004_remove_contenttourist_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttourist',
            name='is_pdf',
            field=models.BooleanField(default=True, verbose_name='Разрешить PDF'),
        ),
    ]
