# Generated by Django 3.2.19 on 2023-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0005_contenttourist_is_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttourist',
            name='is_doc',
            field=models.BooleanField(default=False, verbose_name='Разрешить DOC'),
        ),
        migrations.AlterField(
            model_name='contenttourist',
            name='is_pdf',
            field=models.BooleanField(default=False, verbose_name='Разрешить PDF'),
        ),
    ]
