# Generated by Django 3.2.19 on 2023-10-10 12:25

import ckeditor.fields
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URl')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Title')),
                ('description', models.CharField(blank=True, max_length=350, verbose_name='Заголовок Description')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок H1')),
                ('image_zast', models.ImageField(blank=True, upload_to=news.models.get_file_image_zast, verbose_name='Заставка новости')),
                ('post', ckeditor.fields.RichTextField()),
                ('introtext', models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('category', models.CharField(choices=[('agent', 'Новости агентам'), ('turist', 'Новости туристам')], default='turist', max_length=16, verbose_name='Категория новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('title',),
            },
        ),
    ]
