# Generated by Django 4.2.5 on 2023-09-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('title',), 'verbose_name': 'новости', 'verbose_name_plural': 'Новость'},
        ),
    ]
