# Generated by Django 4.2.5 on 2023-09-20 11:58

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('title',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='image_zast',
            field=models.ImageField(blank=True, upload_to=news.models.get_file_image_zast, verbose_name='Заставка новости'),
        ),
    ]
