# Generated by Django 3.2.19 on 2023-10-10 12:29

from django.db import migrations, models
import django.db.models.deletion
import tour.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tour.models.get_file_image_foto, verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.zagrantour', verbose_name='Тур')),
            ],
        ),
    ]
