# Generated by Django 3.2.19 on 2023-10-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_gallerytour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerytour',
            options={'ordering': ('tour',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
