# Generated by Django 3.2.19 on 2023-10-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_gallerytour_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zagrantour',
            name='published_date',
        ),
    ]
