# Generated by Django 3.2.19 on 2023-10-10 12:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('phone1', models.CharField(blank=True, max_length=25, verbose_name='Основной телефон')),
                ('phone1_viber', models.BooleanField(default=False, verbose_name='Есть Viber')),
                ('phone1_teleg', models.BooleanField(default=False, verbose_name='Есть Telegram')),
                ('phone1_whatsapp', models.BooleanField(default=False, verbose_name='Есть WhatsApp')),
                ('phone2', models.CharField(blank=True, max_length=25, verbose_name='Дополнительный телефон')),
                ('phone2_viber', models.BooleanField(default=False, verbose_name='Есть Viber')),
                ('phone2_teleg', models.BooleanField(default=False, verbose_name='Есть Telegram')),
                ('phone2_whatsapp', models.BooleanField(default=False, verbose_name='Есть WhatsApp')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('addr', models.TextField(blank=True, max_length=500, verbose_name='Адрес')),
                ('vk', models.CharField(blank=True, max_length=1000, verbose_name='Вконтакте')),
                ('teleg', models.CharField(blank=True, max_length=1000, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=1000, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=1000, verbose_name='Twitter')),
                ('okdnoklassniki', models.CharField(blank=True, max_length=1000, verbose_name='Одноклассники')),
                ('youtube', models.CharField(blank=True, max_length=1000, verbose_name='YouTube')),
                ('tiktok', models.CharField(blank=True, max_length=1000, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Настройки раздел "Агенствам"',
                'verbose_name_plural': 'Настройки раздел "Агенствам"',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Тип отдыха')),
            ],
            options={
                'verbose_name': 'Тип отдыха',
                'verbose_name_plural': 'Тип отдыха',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TuristamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('phone1', models.CharField(blank=True, max_length=25, verbose_name='Основной телефон')),
                ('phone1_viber', models.BooleanField(default=False, verbose_name='Есть Viber')),
                ('phone1_teleg', models.BooleanField(default=False, verbose_name='Есть Telegram')),
                ('phone1_whatsapp', models.BooleanField(default=False, verbose_name='Есть WhatsApp')),
                ('phone2', models.CharField(blank=True, max_length=25, verbose_name='Дополнительный телефон')),
                ('phone2_viber', models.BooleanField(default=False, verbose_name='Есть Viber')),
                ('phone2_teleg', models.BooleanField(default=False, verbose_name='Есть Telegram')),
                ('phone2_whatsapp', models.BooleanField(default=False, verbose_name='Есть WhatsApp')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('addr', models.TextField(blank=True, max_length=500, verbose_name='Адрес')),
                ('vk', models.CharField(blank=True, max_length=1000, verbose_name='Вконтакте')),
                ('teleg', models.CharField(blank=True, max_length=1000, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=1000, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=1000, verbose_name='Twitter')),
                ('okdnoklassniki', models.CharField(blank=True, max_length=1000, verbose_name='Одноклассники')),
                ('youtube', models.CharField(blank=True, max_length=1000, verbose_name='YouTube')),
                ('tiktok', models.CharField(blank=True, max_length=1000, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Настройки раздел "Туристам"',
                'verbose_name_plural': 'Настройки раздел "Туристам"',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('text_politic', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Статический контент',
                'verbose_name_plural': 'Статический контент',
                'ordering': ['language'],
            },
        ),
    ]
