# Generated by Django 4.2.5 on 2023-09-20 11:58

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('phone1', models.CharField(blank=True, max_length=25, verbose_name='Основной телефон')),
                ('phone2', models.CharField(blank=True, max_length=25, verbose_name='Дополнительный телефон')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('addr', models.TextField(blank=True, max_length=500, verbose_name='Адрес')),
                ('vk', models.CharField(blank=True, max_length=1000, verbose_name='Вконтакте')),
                ('teleg', models.CharField(blank=True, max_length=1000, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=1000, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=1000, verbose_name='Twitter')),
                ('okdnoklassniki', models.CharField(blank=True, max_length=1000, verbose_name='Одноклассники')),
                ('youtube', models.CharField(blank=True, max_length=1000, verbose_name='YouTube')),
                ('tiktok', models.CharField(blank=True, max_length=1000, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Настройки раздел "Агенствам"',
                'verbose_name_plural': 'Настройки раздел "Агенствам"',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='TuristamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('phone1', models.CharField(blank=True, max_length=25, verbose_name='Основной телефон')),
                ('phone2', models.CharField(blank=True, max_length=25, verbose_name='Дополнительный телефон')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('addr', models.TextField(blank=True, max_length=500, verbose_name='Адрес')),
                ('vk', models.CharField(blank=True, max_length=1000, verbose_name='Вконтакте')),
                ('teleg', models.CharField(blank=True, max_length=1000, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=1000, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=1000, verbose_name='Twitter')),
                ('okdnoklassniki', models.CharField(blank=True, max_length=1000, verbose_name='Одноклассники')),
                ('youtube', models.CharField(blank=True, max_length=1000, verbose_name='YouTube')),
                ('tiktok', models.CharField(blank=True, max_length=1000, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Настройки раздел "Туристам"',
                'verbose_name_plural': 'Настройки раздел "Туристам"',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('text_politic', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Политики конфидициальности ')),
            ],
            options={
                'verbose_name': 'Статический контент',
                'verbose_name_plural': 'Статический контент',
                'ordering': ['language'],
            },
        ),
    ]
