# Generated by Django 3.2.19 on 2023-10-18 16:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('text_politica', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Статический контент',
                'verbose_name_plural': 'Статический контент',
                'ordering': ['language'],
            },
        ),
    ]
