# Generated by Django 3.2.19 on 2023-09-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turistamsettings',
            name='phone1_teleg',
            field=models.BooleanField(default=False, verbose_name='Есть Telegram'),
        ),
        migrations.AddField(
            model_name='turistamsettings',
            name='phone1_viber',
            field=models.BooleanField(default=False, verbose_name='Есть Viber'),
        ),
        migrations.AddField(
            model_name='turistamsettings',
            name='phone1_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Есть WhatsApp'),
        ),
        migrations.AddField(
            model_name='turistamsettings',
            name='phone2_teleg',
            field=models.BooleanField(default=False, verbose_name='Есть Telegram'),
        ),
        migrations.AddField(
            model_name='turistamsettings',
            name='phone2_viber',
            field=models.BooleanField(default=False, verbose_name='Есть Viber'),
        ),
        migrations.AddField(
            model_name='turistamsettings',
            name='phone2_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Есть WhatsApp'),
        ),
    ]
