# Generated by Django 3.2.19 on 2023-11-15 07:42

import ckeditor.fields
from django.db import migrations, models
import setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_websitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanerTurist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=setting.models.get_file_image_baner, verbose_name='Банер')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
                ('url', models.CharField(blank=True, max_length=10000, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Банеры "Туристам"',
                'verbose_name_plural': 'Банеры "Туристам"',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='agentamsettings',
            options={'ordering': ['language'], 'verbose_name': 'Настройки "Агенствам"', 'verbose_name_plural': 'Настройки "Агенствам"'},
        ),
        migrations.AlterModelOptions(
            name='turistamsettings',
            options={'ordering': ['language'], 'verbose_name': 'Настройки "Туристам"', 'verbose_name_plural': 'Настройки "Туристам"'},
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='text_politica',
            field=ckeditor.fields.RichTextField(verbose_name='Политика конфиденциальности'),
        ),
    ]
