# Generated by Django 3.2.19 on 2023-11-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20231115_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='banerturist',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Название'),
        ),
    ]
