# Generated by Django 3.2.19 on 2023-11-15 09:34

from django.db import migrations, models
import setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_banerturist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=setting.models.get_file_image_baner2, verbose_name='Банер')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Название')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
                ('url', models.CharField(blank=True, max_length=10000, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Банеры "Агентам"',
                'verbose_name_plural': 'Банеры "Агентам"',
                'ordering': ('id',),
            },
        ),
    ]
